#ifndef SPARKLE_CONFIG_H_
#define SPARKLE_CONFIG_H_

#ifndef SPARKLE_PWM_PORT
#define SPARKLE_PWM_PORT PORTB
#endif

#ifndef SPARKLE_PWM_DDR
#define SPARKLE_PWM_DDR DDRB
#endif

#ifndef SPARKLE_PWM_PIN_LTC
#define SPARKLE_PWM_PIN_LTC PB3
#endif

#ifndef SPARKLE_PWM_PIN_CLK
#define SPARKLE_PWM_PIN_CLK PB5
#endif

#ifndef SPARKLE_PWM_PIN_OUT
#define SPARKLE_PWM_PIN_OUT PB4
#endif

#ifndef SPARKLE_CTL_PORT
#define SPARKLE_CTL_PORT PORTD
#endif

#ifndef SPARKLE_CTL_DDR
#define SPARKLE_CTL_DDR DDRD
#endif

#ifndef SPARKLE_CTL_PIN
#define SPARKLE_CTL_PIN PD1
#endif

#endif /* SPARKLE_CONFIG_H_ */
